### ISSUE TITLE
为什么可以连接 wireguard 却不能上网？

### ISSUE THREAD

**Issue by bao3** [hwdsl2/wireguard-install#10]
**任务列表**

- 

- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 WireGuard VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)

- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)

**问题描述**
使用安装脚本顺利安装 wireguard，并且通过扫码添加了 iOS 端的 wireguard 配置。
使用这个配置连接 VPN，成功。
可是我只能 ping 10.7.0.1 (也就是对端的IP），可是我却上不了网。

**重现步骤**

我猜测是不是我的 vps 有问题，于是在 三个不同的 VPS 平台上测试，都是一样状态。
其中，上面说的第一台 vps 是全新安装的 Ubuntu 20.04 ，其他 2 台都是已经有 v2ray 或者 类似软件在运行（这些软件可以正常连接）

**期待的正确结果**
我自己是猜测可能是路由有问题，可是又不知道如何排查，希望可以看看是不是安装时可以顺带做什么设置？或者也可能是 iOS 的问题？
（ 我有 M1 Macboot，也是一样的情况）

**日志**
没有日志，可以正常边接 VPN。

**服务器信息（请填写以下信息）**
- 操作系统: Ubuntu 20.04 / Debian 11
- 服务提供商（如果适用）: Oracle , Bandwagon , Vultr

**客户端信息（请填写以下信息）**
- 设备:  iPhone 14 Pro
- 操作系统:  iOS 16.1.1

**其它信息**
NO。

**Comment by hwdsl2** [comment]
@bao3 你好！我测试了 iOS 可以正常连接并正常访问网站。如果你是从中国境内连接的话，你的 VPN 连接很可能被 GFW 屏蔽或干扰了，导致无法访问网站。对于该用例，你可以另外尝试比如 Shadowsocks。
