### ISSUE TITLE
新增sysctl配置

### ISSUE THREAD

**Issue by lelelemonade** [hwdsl2/wireguard-install#11]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 WireGuard VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)

**描述改进建议**
建议在脚本安装完成后，修改/etc/sysctl.conf，新增如下：
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

**你的改进建议与遇到的问题有关吗？请描述。**
  我按脚本安装完成后发现WiFi连接VPN，无法翻墙，流量连接VPN，可以翻墙。在sysctl.conf增加这些后WiFi也可以翻墙了。我其实不懂这配置的意思，开发者可以评估下。

**Comment by hwdsl2** [comment]
@lelelemonade 你好！感谢你的建议。安装脚本已经包含你所说的配置，它们被写入 /etc/sysctl.d/99-wireguard-forward.conf，作用是一样的。
