### ISSUE TITLE
253 clients are already configured. The WireGuard internal subnet is full!

### ISSUE THREAD

**Issue by hamuraiisam** [hwdsl2/wireguard-install#12]
Hello, I encountered an issue when the subnet is being filled to the limit.

Does the script only work in one subnet? Is it possible to make the script continue creating client certs in additional subnets?

**Comment by hwdsl2** [comment]
@hamuraiisam Hello! The script currently has a limit of 253 WireGuard clients. It is not supported to continue creating client certs in additional subnets. You may be able to customize the script yourself to use a larger subnet instead.
