### ISSUE TITLE
Abort install 

### ISSUE THREAD

**Issue by lexmaxak** [hwdsl2/wireguard-install#13]
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup script, and not WireGuard VPN itself

**Describe the issue**
Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
wireguard.sh: line 652: /etc/wireguard/wg0.conf: No such file or directory
chmod: cannot access '/etc/wireguard/wg0.conf': No such file or directory
+ systemctl enable --now wg-iptables.service
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
wireguard.sh: line 401: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
wg: Key is not the correct length or format
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
+ systemctl enable --now wg-quick@wg0.service

**To Reproduce**

1. Install WG
2. Deinstall WG
3. Install WG

**Expected behavior**

**Logs**
Add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]

**Additional context**

**Comment by hwdsl2** [comment]
@lexmaxak Hello! Thanks for reporting this issue. I could not reproduce this issue on a Ubuntu 22.04 or Debian 11 system. Most likely it's because the command `apt-get -yqq install wireguard qrencode` failed for some reason when you reinstalled WireGuard, and it's not an issue with the script itself.
