### ISSUE TITLE
CentOS 9 client configuration issue

### ISSUE THREAD

**Issue by wtoshopnet** [hwdsl2/wireguard-install#14]
google centos9 why list faild?thanks

**Comment by hwdsl2** [comment]
@wtoshopnet Hello! Not sure what you are asking - please add a comment or open a new issue with more details on the problem.

**Comment by wtoshopnet** [comment]
/
![11730](https://user-images.githubusercontent.com/130846485/232264535-242bbb92-ca08-4679-b6b5-2a3b0f17c509.png)

**Comment by hwdsl2** [comment]
@wtoshopnet Thanks for the additional information. I can try to reproduce this issue when I have time. For now, please try re-installing WireGuard and see if it works. You can also try other Linux versions such as CentOS 7.

**Comment by wtoshopnet** [comment]
Other systems can be installed. I have tested it, but the latest CEONTOS 9 cannot be installed. If you have time, I hope you can solve it
thank you.

**Comment by hwdsl2** [comment]
@wtoshopnet I tested on CentOS 9 Stream and was able to successfully import the client configuration on Windows and connect. I think this may be an issue with your client configuration file. Try re-installing WireGuard on the VPN server, or add a new client on the server and import `client.conf` again.
