### ISSUE TITLE
ubuntu 22.04 manual install

### ISSUE THREAD

**Issue by nickfan** [hwdsl2/wireguard-install#15]
**任务列表**

- [x ] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)
- [x ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [x ] 这个 bug 是关于 VPN 安装脚本，而不是 WireGuard VPN 本身

**问题描述**

![image](https://user-images.githubusercontent.com/100613/232572123-61da3a7e-1509-42a6-a1c0-b75ac250f28f.png)

**重现步骤**
重现该 bug 的步骤：

```bash
sudo bash wireguard.sh

```
```text
Welcome to this WireGuard server installer!
GitHub: https://github.com/hwdsl2/wireguard-install

I need to ask you a few questions before starting setup.
You can use the default options and just press enter if you are OK with them.

Which IPv6 address should be used?
     1) 111xxx
     2) 222xxx
IPv6 address [1]: 1

What port should WireGuard listen to?
Port [51820]:

Enter a name for the first client:
Name [client]:

Select a DNS server for the client:
   1) Current system resolvers
   2) Google Public DNS
   3) Cloudflare DNS
   4) OpenDNS
   5) Quad9
   6) AdGuard DNS
   7) Custom
DNS server [2]: 3

WireGuard installation is ready to begin.
Do you want to continue? [Y/n]

Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
Error: 'apt-get install' failed.
```

**期待的正确结果**
正常安装

**Comment by hwdsl2** [comment]
@nickfan 你好！Ubuntu 22.04 最近的测试已通过（参见[这里](https://github.com/hwdsl2/wireguard-install/actions/runs/4560513281/jobs/8387061554)），可以正常安装。应该是你的服务器的系统的问题，不是脚本的问题。你可以将脚本中的 `apt-get -yqq install` 替换为 `apt-get -y install`，然后再次尝试安装并检查具体的错误信息。

**Comment by VahidN** [comment]
This error happens after installing and then uninstalling it.

**Comment by hwdsl2** [comment]
@VahidN Hello! The referenced error typically means that `apt-get -yqq install wireguard qrencode iptables` was not successful, therefore the `/etc/wireguard` folder was not created. The script catches this issue and return an error. Please retry the install on your server, as it is usually a temporary issue.
