### ISSUE TITLE
请问怎么修改IP地址段呢，因为我有两台服务器对接一个设备，都是使用你的脚本就冲突了

### ISSUE THREAD

**Issue by Eric-168** [hwdsl2/wireguard-install#17]
请问怎么修改IP地址段呢，因为我有两台服务器对接一个设备，都是使用你的脚本就冲突了

**Comment by hwdsl2** [comment]
@Eric-168 你好！本项目目前不支持自定义IP地址段。你可以自己编辑脚本并替换所有相关的IP地址段，然后运行你的修改后的版本。
