### ISSUE TITLE
fully disable the logs

### ISSUE THREAD

**Issue by HXMCPP** [hwdsl2/wireguard-install#19]
**Checklist**

- [ ] I m looking to implement it with no actual logs

**Describe the enhancement request**
A clear and concise description of an implementation with no logs

**Comment by hwdsl2** [comment]
@HXMCPP Hello! This is not currently supported in the WireGuard setup script in this project. Because the standard WireGuard package from your Linux distribution is installed by the script, you can look into this yourself by searching for e.g. WireGuard disable logging on the Internet.
