### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by HLFH** [hwdsl2/wireguard-install#20]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [x] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
The script should add Arch Linux support

**Is your enhancement request related to a problem? Please describe.**
No

**Additional context**
Well most of the wireguard-install script either don't support Arch Linux or barely support it. So it would be great for this script to support it.

**Comment by hwdsl2** [comment]
@HLFH Hello! Thank you for your suggestion. Currently, there is no plan for this project to support Arch Linux.
