### ISSUE TITLE
command: wg show, shows a different public key than imported to the client

### ISSUE THREAD

**Issue by shag00** [hwdsl2/wireguard-install#23]
**Describe the issue**
I followed the instructions and used the qr code to setup the peer on my android which displays 2 public keys:
SzZkNHW... and
bC4Dsw8...

![WhatsApp Image 2023-08-22 at 9 19 07 AM](https://github.com/hwdsl2/wireguard-install/assets/37562304/af5db80f-0925-4147-907e-7ef304f07ee6)

My wg0.conf file on the server:
`[Interface]
Address = 10.7.0.1/24, fddd:2c4:2c4:2c4::1/64
PrivateKey = 8D...
ListenPort = 51820

# BEGIN_PEER client
[Peer]
PublicKey = SzZkNHWC...
PresharedKey = vE...
AllowedIPs = 10.7.0.2/32, fddd:2c4:2c4:2c4::2/128
# END_PEER client`

So far seems to be OK until I run wg show on the server:
`interface: wg0
  public key: 7TyDV3k/7I5pR4ARYaPhtfoRRWvcWvAMNLcmcwoLiiI=
  private key: (hidden)
  listening port: 51820`

Running wg syncconf or wg setconf both return this error:
`scott@scottlounge:~$ sudo wg setconf wg0 /etc/wireguard/wg0.conf
Line unrecognized:  Address=10.7.0.1/24,fddd:2c4:2c4:2c4::1/64
Configuration parsing error`

I believe the public key, 7TyDV3k/7I5pR4ARYaPhtfoRRWvcWvAMNLcmcwoLiiI= was a key created by an earlier key generation attempt by me.

**Expected behavior**
That the wg0.conf file that did not exist prior to running the install script contains the server key that the script generated.

**Logs**
Add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Kubuntu 23.04
- Hosting provider: N/A

**Client (please complete the following information)**
- Device: Redmi Note 12 pro plus
- OS:  MIUI 14.0.6.0 / Android 12 SP1A.210812.016

**Comment by hwdsl2** [comment]
@shag00 Hello! From the details you provided, it looks like you have multiple wireguard binaries, configuration files or services running on your server. This doesn't look like a bug in wireguard-install.sh.

While I can't help you troubleshoot on your server, I would suggest that you search for and uninstall all wireguard instances from the server along with their configurations (you can check e.g. `ps aux` to see the running instances), then re-install using the script in this repo.

**Comment by shag00** [comment]
Thanks for your reply, an uninstall and restart seems to have fixed the problem.
