### ISSUE TITLE
服务器重启了，wireguard没有开机自启动呢

### ISSUE THREAD

**Issue by zzfree2021** [hwdsl2/wireguard-install#24]
系统：轻量云centos7.6
问题：安装过程正常，但是服务器重启后，wireguard没有开机自启动。
需要怎么手动启动呢或者加入开机自启动

**Comment by hwdsl2** [comment]
@zzfree2021 你好！请运行：
```
systemctl restart wg-iptables.service
systemctl restart wg-quick@wg0.service
```
脚本默认配置 WireGuard 开机自启动。如果自启动不工作，你可以将以上命令添加到 `/etc/rc.local`。
