### ISSUE TITLE
作者你好，我想咨询一下分流的问题还有就是wireguard数据传输安全吗

### ISSUE THREAD

**Issue by MaybeQHL** [hwdsl2/wireguard-install#25]
作者你好，我想咨询一下分流的问题还有就是wireguard数据传输安全吗

**Comment by hwdsl2** [comment]
@MaybeQHL 你好！目前本项目不支持 VPN 分流。WireGuard 采用自己的协议，具体参见 https://www.wireguard.com。如需 VPN 分流，你也可以考虑其他解决方案。
