### ISSUE TITLE
Regenerate QR code

### ISSUE THREAD

**Issue by shag00** [hwdsl2/wireguard-install#29]
**Checklist**

- [ x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x ] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [x ] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [ x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
When running `sudo bash wireguard.sh` after having setup the server and clients the following options are available:
   1) Add a new client
   2) List existing clients
   3) Remove an existing client
   4) Remove WireGuard
   5) Exit

It would be quite helpful to add a 6th option, regenerate QR code for existing client.  This would be most useful when people update their phones and reinstall everything and in the instances where people want to access with their PC as well as their phone (one person, 2 devices).

**Is your enhancement request related to a problem? Please describe.**
No everything works reliably.

**Additional context**

**Comment by hwdsl2** [comment]
@shag00 Hello! Thank you for your suggestion, it will be considered for future enhancements in this project. In the meantime, you may regenerate the QR code by running:
```
qrencode -t UTF8 < /root/client.conf
```
Replace `/root/client.conf` with the full path to the client configuration file generated by the script for the VPN client in question.

**Comment by shag00** [comment]
I ran `qrencode -t UTF8 < /etc/wireguard/wg0.conf` as advised and received a QR code. The trouble is there are numerous clients and only 1 Qr code. How to specify what client QR code I want?

**Comment by hwdsl2** [comment]
@shag00 This is incorrect:
```
qrencode -t UTF8 < /etc/wireguard/wg0.conf
```
Instead, you may run:
```
qrencode -t UTF8 < /root/your_client_name.conf
```
Replace `your_client_name.conf` with the actual client configuration file created earlier when you added the client. You can find them under `root` or your `sudo` user's home directory. If you've deleted them, you'll need to run the script to add a new client instead.

**Comment by shag00** [comment]
OK, thank you for that. What threw me was that the conf files are stored in my home directory not my root directory.
