### ISSUE TITLE
连上了但是Ping不通 

### ISSUE THREAD

**Issue by ihuaer** [hwdsl2/wireguard-install#30]
一开始用的hwdsl2提供的一键openvpn ，突然有一天连不上了
又改用wireguard，可以连但是ping不通

不知道怎么回事，家里是电信公网ip。不知道如何排查问题，有没有可能ip被阻断了
通过阿里云域名是可以正常访问家里设备的

**Comment by hwdsl2** [comment]
@ihuaer 你好！从你提供的信息来看，可能是连接被 GFW 屏蔽了。建议尝试其他解决方案，比如 Shadowsocks 等。

**Comment by kouzhudong** [comment]
我也出现了这个情况，然后用建议的Shadowsocks成功了。

**Comment by stockbsd** [comment]
> [@ihuaer](https://github.com/ihuaer) 你好！从你提供的信息来看，可能是连接被 GFW 屏蔽了。建议尝试其他解决方案，比如 Shadowsocks 等。

那请问 如何更改51820端口，也就是换个端口躲避gfw。
我的wg，装好一天后用的挺好，第二天看起来就像被封了-连不上了
