### ISSUE TITLE
The internet is not accessible

### ISSUE THREAD

**Issue by azharrasheed** [hwdsl2/wireguard-install#33]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)
- [x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup script, and not WireGuard VPN itself

**Describe the issue**
After the auto successful installation amazon ec2 ubuntu server . I connected to it on android and also tried to connect to it on laptop, but to no avail. no internet connection 

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
Add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]

**Additional context**

**Comment by hwdsl2** [comment]
@azharrasheed Hello! Please make sure that you have opened UDP port 51820 in your Amazon EC2 server's [security group](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html). The script in this repo has been tested and worked fine in those tests.

WireGuard VPNs can be blocked by firewalls such as the GFW in mainland China. For those use cases please look into alternative solutions such as Shadowsocks.
