### ISSUE TITLE
Add gui prompt for wireguard private subnet

### ISSUE THREAD

**Issue by JonEhh90** [hwdsl2/wireguard-install#35]
Everything currently defaults to 10.7.0.0/24. Please allow custom private subnet entry. Also please store all variables/parms in a config file in like /etc/wireguard/config so when you run the script again it can get this data.

Reason for request is the script also makes wg-iptables.service in systemd and if someone just thought they had to edit wg0.conf and change the server ip then everything would just work. No you have to go edit the iptables as well.

Thanks!

**Comment by hwdsl2** [comment]
@JonEhh90 Hello! Thank you for your suggestions. These are not currently planned in this project. However, you may customize the script for your use case.
