### ISSUE TITLE
Better bash integration for custom installing

### ISSUE THREAD

**Issue by zden2ksobotka** [hwdsl2/wireguard-install#36]
**Describe the enhancement request**

Hello,
I found your script and I think it's amazing. I would like to recommend it, in our hosting as an installation script to install VPN to our clients. In that context, I wanted to ask if you are considering extend the vpn script to control it in bash command line. Something like:

INSTALL:
`bash wireguard.sh --install --name vpn.server.tld --port 58920 --dns 8.8.8.8`

USAGE:
```
bash wireguard.sh --add-client username
bash wireguard.sh --remove-client username
bash wireguard.sh --lists-client
bash wireguard.sh --show-client-qr username
bash wireguard.sh --show-client-qr username --export-path <path>.png
```

REMOVE:
`bash wireguard.sh --uninstall`

**Comment by hwdsl2** [comment]
@zden2ksobotka Hello! First, thank you for your support through GitHub Sponsors! The feature you mentioned is not currently available, but I think it could be a valuable addition to the script. Unfortunately, I have been busy recently, so while I plan to look into this, I can't make any guarantees on when this feature will be available.

In the meantime, you can use Bash "here documents" to specify the parameters during installation or user management. Please refer to the section [Installation](https://github.com/hwdsl2/wireguard-install#installation) in the README, and expand "Advanced: Auto install using custom options" to see details.

**Comment by hwdsl2** [comment]
@zden2ksobotka As requested, I have made improvements to both the [WireGuard script](https://github.com/hwdsl2/wireguard-install) and the [OpenVPN script](https://github.com/hwdsl2/openvpn-install) to support command-line options for managing VPN clients and removing WireGuard/OpenVPN. See below for usage information for the current versions of the scripts. You can also find them in the "Installation" sections in the README documents of the two projects.

Currently, the install process for WireGuard/OpenVPN do not yet support command-line options. This is more complicated and can be added in a future improvement. For now, please continue to use the Bash "here documents" method to specify the parameters during custom installation.

```
Usage: bash wireguard.sh [options]

Options:
  --auto                        auto install WireGuard using default options
  --addclient [client name]     add a new client
  --dns1 [DNS server IP]        primary DNS server for new client (optional, defaults to Google Public DNS)
  --dns2 [DNS server IP]        secondary DNS server for new client (optional)
  --listclients                 list the names of existing clients
  --removeclient [client name]  remove an existing client
  --showclientqr [client name]  show QR code for an existing client
  --uninstall                   remove WireGuard and delete all configuration
  -y, --yes                     assume "yes" as answer to prompts when removing a client or removing WireGuard
  -h, --help                    show this help message and exit

To customize install options, run this script without arguments.
```

```
Usage: bash openvpn.sh [options]

Options:
  --auto                        auto install OpenVPN using default options
  --addclient [client name]     add a new client
  --exportclient [client name]  export configuration for an existing client
  --listclients                 list the names of existing clients
  --revokeclient [client name]  revoke an existing client
  --uninstall                   remove OpenVPN and delete all configuration
  -y, --yes                     assume "yes" as answer to prompts when revoking a client or removing OpenVPN
  -h, --help                    show this help message and exit

To customize install options, run this script without arguments.
```

**Comment by zden2ksobotka** [comment]
Hello @hwdsl2, Thank you for the improvements that has been added to the script. Great, I appreciate it.

**Comment by hwdsl2** [comment]
@zden2ksobotka I have added support for command-line install options for both the WireGuard and OpenVPN scripts. See the project README documentation for usage information. These options may change in future versions of the scripts. Example:
```
bash wireguard.sh --auto --serveraddr example.com --port 58920 --clientname client1 --dns1 1.1.1.1 --dns2 1.0.0.1
```
