### ISSUE TITLE
No internet on clients.

### ISSUE THREAD

**Issue by paul-on** [hwdsl2/wireguard-install#38]
I installed the script. I add a client. Using QR code I set up a VPN tunnel on a mobile device. Then when on a mobile devise I switch VPN "**ON**" it loses any internet. No one website is loaded.
I believe the script works fine but the problem is with my VPS. I don't have the proper knowledge to figure out the reason for my own. So I would be glad to get some assistance. Also I didn't have any progress while googling this issue.

There're some logs from my VPS that may ease to find the solution.
`sudo ss -tulpn`
```
Netid   State    Recv-Q   Send-Q     Local Address:Port      Peer Address:Port  Process
udp     UNCONN   0        0          127.0.0.53%lo:53             0.0.0.0:*      users:(("systemd-resolve",pid=654,fd=12))
udp     UNCONN   0        0                0.0.0.0:51820          0.0.0.0:*
udp     UNCONN   0        0                   [::]:51820             [::]:*
tcp     LISTEN   0        4096       127.0.0.53%lo:53             0.0.0.0:*      users:(("systemd-resolve",pid=654,fd=13))
tcp     LISTEN   0        128              0.0.0.0:22             0.0.0.0:*      users:(("sshd",pid=788,fd=3))
tcp     LISTEN   0        128                 [::]:22                [::]:*      users:(("sshd",pid=788,fd=4))
```

`sudo iptables --line-numbers -nvL`
```
Chain INPUT (policy ACCEPT 87 packets, 8274 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     9741 1225K f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22
2        5   608 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:51820

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1        3   551 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
2        3   186 ACCEPT     all  --  *      *       10.7.0.0/24          0.0.0.0/0

Chain OUTPUT (policy ACCEPT 140 packets, 20467 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain f2b-sshd (1 references)
num   pkts bytes target     prot opt in     out     source               destination
1       16   896 REJECT     all  --  *      *       43.156.59.212        0.0.0.0/0            reject-with icmp-port-unreachable
2       26  1928 REJECT     all  --  *      *       123.30.249.49        0.0.0.0/0            reject-with icmp-port-unreachable
3       30  2208 REJECT     all  --  *      *       165.22.57.6          0.0.0.0/0            reject-with icmp-port-unreachable
4     6944 1029K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

`sudo iptables -nvL -t nat`
```
Chain PREROUTING (policy ACCEPT 61334 packets, 7371K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 14194 packets, 1237K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 349 packets, 29797 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 349 packets, 29797 bytes)
 pkts bytes target     prot opt in     out     source               destination
    3   186 MASQUERADE  all  --  *      *       10.7.0.0/24         !10.7.0.0/24
```

Feel free to ask any additional information.

**Comment by hwdsl2** [comment]
@paul-on Hello! Thanks for posting the detailed output. The IPTables rules in the output look fine, and the WireGuard service appears to be listening on UDP port 51820. Here are some possible reasons and things to try:

1. Check that DNS resolution works on the VPS, and that you can connect to websites. For example, you can run `dig -t A -4 www.google.com +short` to see if it returns a set of IP(s) for this domain, and run `curl -fsSL https://www.example.com` to see if it returns the HTML of that website's home page.
2. Reboot your client device, then re-try the connection.
3. Use a different client device to connect to the VPN server. This can help check whether the issue is with the server itself, or with the client.

You can also try setting up the VPN on a new server from a different provider. The WireGuard script in this project has been tested and should work for common use cases. If you have additional information or updates feel free to reply here.

**Comment by paul-on** [comment]
1. `dig -t A -4 www.google.com +short`
Returns the only one IP:
`216.58.209.36`

`curl -fsSL https://www.example.com`
Returns HTML, it's okay.

2. It didn't help.
3. I tried on two different devices.

I'm still looking for an answer in web, trying apply different configurations to different objects of my VPS but still don't have success.

Changing VPS is too easy way. I would like to figure out is it possible to set it up on my current VPS which is on Arubacloud. I suppose that the reason is in VPS configuration.

**Comment by paul-on** [comment]
By the way [IPsec VPN](https://github.com/hwdsl2/setup-ipsec-vpn) on the same VPS is working. So, I can make a conclusion that WireGuard is not so good.
