### ISSUE TITLE
Domens config

### ISSUE THREAD

**Issue by svatrous** [hwdsl2/wireguard-install#4]
Hi, thank you so much for this script. 
Can you please give me an advice how can I config VPN to work only with special sites? 

Thank you again

**Comment by hwdsl2** [comment]
@svatrous Hello! This feature is not supported in this project.

**Comment by rim99** [comment]
To enable VPN for specific site only, it can be done by tunning iptables.

For example, customize this line to meet your requirement

https://github.com/hwdsl2/wireguard-install/blob/005b15b60e1a38f838f289f1395f6601ed3fd0bb/wireguard-install.sh#L677

I've tested this on my system.

@svatrous
