### ISSUE TITLE
Deepin v23使用脚本安装wireguard时报错

### ISSUE THREAD

**Issue by LibraStalker** [hwdsl2/wireguard-install#40]
**任务列表**

- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 WireGuard VPN 本身

**问题描述**
我的操作系统为Deepin v23，使用该脚本安装wireguard提示如下：
`Error: Debian 11 or higher is required to use this installer.
This version of Debian is too old and unsupported.
`
不知道是不是改脚本不支持deepin v23的原因，或者可以提供解决方法吗？

**重现步骤**
重现该 bug 的步骤：

1. `wget -O wireguard.sh https://get.vpnsetup.net/wg`
2. `bash wireguard.sh --serveraddr 174.28.3.10 --clientname xiaomi-13 --dns1 223.5.5.5 --dns2 223.6.6.6`

**日志**
添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: Deepin v23
- 服务提供商（如果适用）: [比如 GCP, AWS]

**Comment by hwdsl2** [comment]
@LibraStalker 你好！本项目目前不支持 Deepin Linux。你可以尝试修改脚本并去掉和以上错误相关的检查，但该方法不推荐，可能仍然不能正常安装和使用。建议你换用一个受支持的 Linux 发行版，参见本项目自述文件的说明。
