### ISSUE TITLE
Generate ipv6 ips instead of a default one

### ISSUE THREAD

**Issue by DorianCoding** [hwdsl2/wireguard-install#41]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [x] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
It seems by default, the ipv6 range fddd:2c4:2c4:2c4::/64 is used. It would be better to get a random ipv6 range as described in [RFC 4193](https://www.rfc-editor.org/rfc/rfc4193#ref-ADDARCH). This is also critical if numerous Wireguards instances are created in the same VLAN, as the risk of address conflicts is certain.

It is also true for ipv4 but it cannot really be changed unless a random number is taken from 10.X ranges (which still gives 65 535 Ips for each instance).

**Is your enhancement request related to a problem? Please describe.**
If many instances of Wireguard exists in the same VLAN, different machines would share the same ipv6 address.

Thanks.

**Comment by hwdsl2** [comment]
@DorianCoding Hello! Thank you for your suggestions. This feature is not currently planned in this project. However, you are welcome to customize the script according to your use case.
