### ISSUE TITLE
[Feature Request] backup restore feature

### ISSUE THREAD

**Issue by PGRjoystick** [hwdsl2/wireguard-install#42]
**Checklist**

- [✓] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [✓] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [✓] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [✓] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
add a feature to backup and restore list of the registered clients and their keys. so that the client doesn't need to replace the config file if we reinstalling the wireguard server

**Additional context**
this is really useful when we need to reinstall our server or migrating to a new one

**Comment by hwdsl2** [comment]
@PGRjoystick Hello! Thank you for your suggestions. This feature is not currently planned for this project. However, you are welcome to customize the script to your needs.

When using the script from this project, the `/etc/wireguard` folder stores WireGuard server configuration, while the client configuration `.conf` files are generated under `/root` (or your home folder, if using `sudo`). You can back up those folders and files as a starting point. Check the script to see if there are other places where WireGuard configuration is stored.
