### ISSUE TITLE
+ apt-get -yqq install wireguard qrencode Error: 'apt-get install' failed.

### ISSUE THREAD

**Issue by mwbreur** [hwdsl2/wireguard-install#44]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)
- [x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup script, and not WireGuard VPN itself

**Describe the issue**
1 Download wget -O wireguard.sh https://get.vpnsetup.net/wg
2 sudo bash wireguard.sh --auto
3 error  root@nc:/home/silence# sudo bash wireguard.sh --auto

WireGuard Script
https://github.com/hwdsl2/wireguard-install

Starting WireGuard setup using default options.

Server IP: redacted
Port: UDP/51820
Client name: client
Client DNS: Google Public DNS

Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
Error: 'apt-get install' failed.
root@nc:/home/silence#

**To Reproduce**

1 Download wget -O wireguard.sh https://get.vpnsetup.net/wg
2 sudo bash wireguard.sh --auto
3 error  root@nc:/home/silence# sudo bash wireguard.sh --auto

WireGuard Script
https://github.com/hwdsl2/wireguard-install

Starting WireGuard setup using default options.

Server IP: redacted
Port: UDP/51820
Client name: client
Client DNS: Google Public DNS

Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
Error: 'apt-get install' failed.
root@nc:/home/silence#

**Expected behavior**
No clue never used it before, but i assume it just installs the rest.

**Logs**
no logs

**Server (please complete the following information)**
- Ubuntu 24.10 (latest)

**Client (please complete the following information)**
not available

**Additional context**
expected it to install and continue setup

**Comment by mwbreur** [comment]
Sorry for the bother, i already tried it manually because i wanted to route traffic through adguard. It seems some other things were installed?
Had to run : root@nc:/# apt remove wireguard-go wireguard-tools wireguard and rerun script now goes fine. 

Maybe add a message if those things are installed?

**Comment by hwdsl2** [comment]
@mwbreur Hello! Thanks for the update. Yes, it looks like your system had packages like "wireguard-go" installed, which prevented the script from working the first time. Glad you were able to fix it.

**Comment by dFelinger** [comment]
Same error
Fixed by manually creating dir: /etc/wireguard
Script doesn't create it in install_pkgs for ubuntu and debian

**Comment by hwdsl2** [comment]
@dFelinger Hello! What is your server's OS version (e.g. Ubuntu 24.04)? The check for /etc/wireguard was added (in 407cb93) was because when `apt-get install` succeeds, the `/etc/wireguard` folder would normally already be created.

**Comment by dFelinger** [comment]
Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-136-generic x86_64)

It happened once.
After creating dir, issue disappeared - deleting and reinstalling wireguard with script runs fine.
