### ISSUE TITLE
添加可以在lxc或者docker安装的支持

### ISSUE THREAD

**Issue by skill7899** [hwdsl2/wireguard-install#5]
**任务列表**

- [✓ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [✓ ] 这个改进建议是关于 VPN 安装脚本，而不是 WireGuard VPN 本身
- [ ✓] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)
- [ ✓] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
现在这个脚本不能运行在lxc里面或者docker里面，

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。
WireGuard本身是可以运行在docker或者lxc里面的，只要给权限就可以了，还有映射tun

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@skill7899 你好！感谢你的建议。该功能超出了本项目的范围。建议你查找网上其他项目关于WireGuard的Docker镜像。

**Comment by skill7899** [comment]
> @skill7899 你好！感谢你的建议。该功能超出了本项目的范围。建议你查找网上其他项目关于WireGuard的Docker镜像。

我发现你的脚本是可以装的，只要去掉检测就OK，其实可以做个判断，有没有tun设备就可以了。有tun设备就让他装

**Comment by hwdsl2** [comment]
@skill7899 该脚本是基于 https://github.com/Nyr/wireguard-install，那个项目是支持container的。但是它选择使用 BoringTun 并从网上下载一个 BoringTun binary。这可能是因为 WireGuard 内核模块不能从 container 内部安装。本项目移除了该部分代码，去掉了 container 支持。如果你感兴趣可以参见 https://github.com/Nyr/wireguard-install。
