### ISSUE TITLE
Support openSUSE

### ISSUE THREAD

**Issue by rim99** [hwdsl2/wireguard-install#6]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [x] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
Add support for openSUSE Linux system.

**Is your enhancement request related to a problem? Please describe.**
Currently, openSUSE is not supported by the installation script.

**Additional context**
None

**Comment by hwdsl2** [comment]
@rim99 Thank you for contributing! I plan to review and test your PR #7 when I have time. In the meantime, I'll close this issue.
