### ISSUE TITLE
Ability to view some information about clients

### ISSUE THREAD

**Issue by Futyn-Maker** [hwdsl2/wireguard-install#8]
**Checklist**

- [X] I searched existing [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [X] This enhancement request is about the VPN setup script, and not WireGuard VPN itself
- [X] I read the [README](https://github.com/hwdsl2/wireguard-install/blob/master/README.md)
- [X] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients.md)

**Describe the enhancement request**
It would be nice to see some information about clients, such as time of last connection and traffic that it spends, in the list of clients. I don't suggest implementing ability of logging, just some general information that would allow to know about traffic spending and time of use.

**Is your enhancement request related to a problem? Please describe.**

**Additional context**

**Comment by hwdsl2** [comment]
@Futyn-Maker Hello! Thank you for your suggestion. This feature is outside the scope of this project. However, you can refer to the WireGuard documentation to see whether there is a way to get these stats from the WireGuard binary or related utilities.
