### ISSUE TITLE
 Error: This system is running inside a container, which is not supported by this installer. "openvz"

### ISSUE THREAD

**Issue by sinamoradzadeh** [hwdsl2/wireguard-install#9]
**任务列表**

- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/wireguard-install/blob/master/docs/clients-zh.md)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/wireguard-install/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 WireGuard VPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...

Error: This system is running inside a container, which is not supported by this installer.

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@sinamoradzadeh 你好！本项目不支持 OpenVZ VPS。你可以另外尝试 https://github.com/Nyr/wireguard-install。
